// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9tm-UKp1q9RNatWjD_8wz_1lPCd8IHX8',
    appId: '1:713687942716:web:c4ac6d0bfd8924a8a86539',
    messagingSenderId: '713687942716',
    projectId: 'chat-app-76800',
    authDomain: 'chat-app-76800.firebaseapp.com',
    storageBucket: 'chat-app-76800.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWN7DNjMWUZTOibtCUSnp_exFw-cL4C8M',
    appId: '1:713687942716:android:4ee2a0a1c85b0cf0a86539',
    messagingSenderId: '713687942716',
    projectId: 'chat-app-76800',
    storageBucket: 'chat-app-76800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_5SfWM-q-GCW0lFG5dJTrDmSaKzQOR0',
    appId: '1:713687942716:ios:924bb1cd51a5c4f5a86539',
    messagingSenderId: '713687942716',
    projectId: 'chat-app-76800',
    storageBucket: 'chat-app-76800.appspot.com',
    androidClientId: '713687942716-qfgkoniir7ijsnska1dnt77nfk5ejcve.apps.googleusercontent.com',
    iosClientId: '713687942716-o9u2h54ggrrfbuc3tfuk27qfqj9qnamt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_5SfWM-q-GCW0lFG5dJTrDmSaKzQOR0',
    appId: '1:713687942716:ios:924bb1cd51a5c4f5a86539',
    messagingSenderId: '713687942716',
    projectId: 'chat-app-76800',
    storageBucket: 'chat-app-76800.appspot.com',
    androidClientId: '713687942716-qfgkoniir7ijsnska1dnt77nfk5ejcve.apps.googleusercontent.com',
    iosClientId: '713687942716-o9u2h54ggrrfbuc3tfuk27qfqj9qnamt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
